//! Auto-generated by `progenitor` at build time from
//! `docs/generated/openapi.json`. DO NOT EDIT — `build.rs` regenerates this
//! on every cargo invocation.
//!
//! This module is included primarily so the generated Rust compiles and
//! becomes a CI gate against upstream-spec drift. The bot's runtime code
//! still consumes the hand-written types in `super::types` (see
//! `docs/exec-plans/completed/002-progenitor-codegen.md`). When/if those
//! get swapped to re-exports from this module, every consumer just changes
//! its import path.

#![allow(
    unused_imports,
    dead_code,
    clippy::all,
    missing_docs,
    renamed_and_removed_lints
)]

include!(concat!(env!("OUT_DIR"), "/explorer_generated.rs"));
